### ISSUE TITLE
Add community health files to this repo to act as a default for the AZ Digital org

### ISSUE THREAD

**Issue by slaymoore** [az-digital/.github#1]
Follow [documentation](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) to add community health files, such as contributing, issue and pull request templates, etc. This will also involve removing these docs from existing repos they have been added to, including az-digital, az-quickstart-scaffolding, and arizona-bootstrap.

**Comment by joeparsons** [comment]
I copied the files from the AZ Quickstart repo.  The CONTRIBUTING.md file is pretty Quickstart-specific so maybe I shouldn't have copied that one.

**Comment by joeparsons** [comment]
It doesn't look like the `.github/CODEOWNERS` file is a supported community health file type so we should probably remove that file.

**Comment by trackleft** [comment]
For the CODE_OF_CONDUCT.md we can probably just add a link in that file to the policy repo

`##  The Arizona Digital [Contributor Covenant Code of Conduct](https://github.com/az-digital/policies/blob/master/code-of-conduct.md)`

Or move the code of conduct from the policies to this repo.

**Comment by slaymoore** [comment]
It looks like the policies document @trackleft linked to is not actually filled out. There's an "[INSERT EMAIL ADDRESS]" in it, but other than that, I think linking to it would be a good idea.
