### ISSUE TITLE
Create README.md for the az-digital namespace.

### ISSUE THREAD

**Issue by trackleft** [az-digital/.github#6]
## Motivation
Every time I go to https://github.com/az-digital I feel like more could be done to make it easier to navigate our namespace.

See documentation about this here: https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

### Is your feature request related to a problem? Please describe.
Difficult to understand our Github presence 

## Proposed Resolution
Make our front page better.

**Comment by Krystation** [comment]
@trackleft 
https://github.com/az-marketing/.github/blob/main/profile/README.md

Hey, I made a readme for it Let me know if I'm okay to just add it in, or who else to tag in here for feedback.

**Comment by trackleft** [comment]
Thank you, Please create a Pull Request on https://github.com/az-digital/.github against the main branch.
